global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Business.Abstract;
global using Autofac;
global using Business.Constants;
global using DataAccess.Abstract;
global using Entities.Concrete;
global using Entities.Dtos;
global using Business.Concrete;
global using Business.DependencyResolvers.Autofac;